### ISSUE TITLE
why l2switch lithium release still use karaf 3.0.1 while other projects have been used karaf 3.0.3?

### ISSUE THREAD

**Issue by Jack2code** [opendaylight/l2switch#1]
I checkout the lithium release of l2switch, but i can not run the karaf correctly.
I read the karaf.log and find most of the bundle installed but can not active.
And then I find out that the pom.xml under l2switch points to karaf 3.0.1 not 3.0.3.
I run the karaf sucessfully with bundles active!

**Comment by tykeal** [comment]
Please open bugs at https://bugs.open daylight.org or ask questions on https://ask.opendaylight.org or the appropriate mailing list at https://lists.opendaylight.org.

This GitHub repo is only a mirror.

**Comment by Jack2code** [comment]
OK
